linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosec
    - bodyclose
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  modules-download-mode: readonly